services:
  mysql:
    image: mysql:latest
    container_name: achievements-app
    ports:
      - "3306:3306"

    env_file:
      - "./app/src/main/resources/.env"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 15s
      retries: 5
    networks:
      auto_network:
        ipv4_address: 172.28.0.1
    volumes:
      - goodreads_data:/var/lib/mysql
  # spring:
  #   build: './app'
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - auto_network

volumes:
  goodreads_data:
    driver: local

networks:
  auto_network:
   ipam: 
    driver: default
    config: 
    - subnet: 172.28.0.0/16